version: '3.9'
services:
  frontend:
    build: ./front-end
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    # Os `healthcheck` devem garantir que a aplicação
    # está operacional, antes de liberar o container
  backend:
    container_name: app_backend
    build: ./Back-end
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Os dados abaixo se referem ao container `db`
      # Dica: Relembre aqui da comunicação interna entre containers
      - MONGO_URI=mongodb://127.0.0.1:27018/
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3008"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
  db:
    image: mongo:4.4.14
    container_name: test
    platform: linux/x86_64
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - 27018:27017
    healthcheck:
      test: ["CMD","ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE